### ISSUE TITLE
Split for cars in shapenet

### ISSUE THREAD

**Issue by mods333** [zekunhao1995/DualSDF#2]
Could you share the splits(ids) for cars in shapenet? Right now there the repository only has splits for chairs and planes.

**Comment by zekunhao1995** [comment]
Hi Mohammed, thanks for the comment! 
Since we didn't do reconstruction evaluation on Cars, there is no need to split the dataset. Instead, we have trained the cars model with the full ShapeNet Cars category. Of course we have also removed some very non-watertight shapes in the category (refer to 'sample_sdfs.py' for detail).

**Comment by mods333** [comment]
Thanks
